# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_alu/design_alu.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_alu || ORIG_REF_NAME==design_alu} -quiet] -quiet

# IP: bd/design_alu/ip/design_alu_processing_system7_0_0/design_alu_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_alu_processing_system7_0_0 || ORIG_REF_NAME==design_alu_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_alu/ip/design_alu_ALU_0_1/design_alu_ALU_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_alu_ALU_0_1 || ORIG_REF_NAME==design_alu_ALU_0_1} -quiet] -quiet

# IP: bd/design_alu/ip/design_alu_axi_gpio_0_0/design_alu_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_alu_axi_gpio_0_0 || ORIG_REF_NAME==design_alu_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_alu/ip/design_alu_axi_gpio_1_0/design_alu_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_alu_axi_gpio_1_0 || ORIG_REF_NAME==design_alu_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_alu/ip/design_alu_axi_gpio_2_0/design_alu_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_alu_axi_gpio_2_0 || ORIG_REF_NAME==design_alu_axi_gpio_2_0} -quiet] -quiet

# IP: bd/design_alu/ip/design_alu_axi_gpio_3_0/design_alu_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_alu_axi_gpio_3_0 || ORIG_REF_NAME==design_alu_axi_gpio_3_0} -quiet] -quiet

# IP: bd/design_alu/ip/design_alu_xbar_0/design_alu_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_alu_xbar_0 || ORIG_REF_NAME==design_alu_xbar_0} -quiet] -quiet

# IP: bd/design_alu/ip/design_alu_auto_pc_0/design_alu_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_alu_auto_pc_0 || ORIG_REF_NAME==design_alu_auto_pc_0} -quiet] -quiet

# IP: bd/design_alu/ip/design_alu_ps7_0_axi_periph_0/design_alu_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_alu_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_alu_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_alu/ip/design_alu_rst_ps7_0_50M_0/design_alu_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_alu_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_alu_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: d:/laborator/ALU_project/ALU_project.gen/sources_1/bd/design_alu/design_alu_ooc.xdc
