domain_path: D:\laborator\ALU_project\ALU_platform_v2\export\ALU_platform_v2\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\vivado\Vitis\2024.1\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
