# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/laborator/ALU_project/ALU_project.srcs/sources_1/bd/design_alu/ip/design_alu_axi_gpio_0_0/design_alu_axi_gpio_0_0.xci
# IP: The module: 'design_alu_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/laborator/ALU_project/ALU_project.gen/sources_1/bd/design_alu/ip/design_alu_axi_gpio_0_0/design_alu_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_alu_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/laborator/ALU_project/ALU_project.gen/sources_1/bd/design_alu/ip/design_alu_axi_gpio_0_0/design_alu_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_alu_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/laborator/ALU_project/ALU_project.gen/sources_1/bd/design_alu/ip/design_alu_axi_gpio_0_0/design_alu_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_alu_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/laborator/ALU_project/ALU_project.srcs/sources_1/bd/design_alu/ip/design_alu_axi_gpio_0_0/design_alu_axi_gpio_0_0.xci
# IP: The module: 'design_alu_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/laborator/ALU_project/ALU_project.gen/sources_1/bd/design_alu/ip/design_alu_axi_gpio_0_0/design_alu_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_alu_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/laborator/ALU_project/ALU_project.gen/sources_1/bd/design_alu/ip/design_alu_axi_gpio_0_0/design_alu_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_alu_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/laborator/ALU_project/ALU_project.gen/sources_1/bd/design_alu/ip/design_alu_axi_gpio_0_0/design_alu_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_alu_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
